name: 'Test JSON Types'

on:
  workflow_dispatch:

jobs:
  test-ubuntu:
    name: Test Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Test types
        shell: pwsh
        run: |
          Write-Host "- $($('1' | ConvertFrom-Json).GetType())"
          Write-Host "- $($('{1: 1}' | ConvertFrom-Json).GetType())"
          Write-Host "- $($('[1, 1]' | ConvertFrom-Json).GetType())"

  test-windows:
    name: Test Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Test types
        shell: powershell
        run: |
          Write-Host "- $($('1' | ConvertFrom-Json).GetType())"
          Write-Host "- $($('{1: 1}' | ConvertFrom-Json).GetType())"
          Write-Host "- $($('[1, 1]' | ConvertFrom-Json).GetType())"
